<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ls</string>
	</array>
	<key>name</key>
	<string>LiveScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comment.</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.LiveScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>Block comment.</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.LiveScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.LiveScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double quoted string.</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.LiveScript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.LiveScript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.LiveScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single quoted string.</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.LiveScript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.LiveScript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.LiveScript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>definition.string.quoted.single.LiveScript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.LiveScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String without whitespace.</string>
			<key>match</key>
			<string>(\\)(.*?)(\s)</string>
			<key>name</key>
			<string>string.LiveScript</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interpolated</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#\{</string>
					<key>comment</key>
					<string>Interpolated complex LiveScript expressions within strings.</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>source.LiveScript.embedded.source</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Interpolated simple LiveScript variables within strings.</string>
					<key>match</key>
					<string>\#(\w*)\b</string>
					<key>name</key>
					<string>source.LiveScript.embedded.source</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|on|off|yes|no)\b</string>
					<key>name</key>
					<string>constant.language.boolean.LiveScript</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(null|undefined|void)\b</string>
					<key>name</key>
					<string>constant.language.LiveScript</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.LiveScript</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>All numbers, different bases, decimals, underscores and trailing characters.</string>
					<key>match</key>
					<string>\b(\d{1,2}~[\d\w]+)|(\d+[\d_]*(\.[\d_]+)?(e[+-]?[\d_]+)?(\w*))\b</string>
					<key>name</key>
					<string>constant.numeric.LiveScript</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.LiveScript</string>
	<key>uuid</key>
	<string>3dd79e1c-6cf0-4302-947b-ef00aa5e2a8d</string>
</dict>
</plist>
